name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: default

      - name: Run test suite
        run: pixi run tests
